apiVersion: v1
data:
  onboarding999999-input-schema.json: |
    {
      "$id": "classpath:/schemas/onboarding999999-schema.json",
      "title": "Data Input Schema",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "sampleText": {
          "title": "A sample text",
          "type": "string",
          "description": "Sample text data"
        }
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 01-onboarding999999-resources
