apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
__RESOURCES__
namespace: workflows

configurations:
- config/image-configuration.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - envs:
      - secret.properties
    name: onboarding999999-secret
configMapGenerator:
  - envs:
      - config.properties
    name: onboarding999999-gitops

# Replace dev profile in SonataFlow instance(s), add image and envFrom
patches:
- path: sonataflow-patch.yaml
  target:
    kind: SonataFlow
    name: onboarding999999
images:
- name: serverless-workflow-onboarding999999
  newName: quay.io/rhdh-orchestrator-test/test-infra
  newTag: __IMAGE_TAG__
