apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: onboarding999999
  annotations:
    sonataflow.org/profile: prod
  labels:
    backstage.io/kubernetes-id: onboarding999999
spec:
  persistence:
    postgresql:
      secretRef:
        name: sonataflow-psql-postgresql
        userKey: postgres-username
        passwordKey: postgres-password
      serviceRef:
        name: sonataflow-psql-postgresql
        namespace: sonataflow-infra
        port: 5432
        databaseName: sonataflow
        databaseSchema: onboarding999999
  podTemplate:
    container:
      image: serverless-workflow-onboarding999999
      envFrom:
        - configMapRef:
            name: onboarding999999-gitops
        - secretRef:
            name: onboarding999999-secret
      resources: {}
